name: build docker
on:
  workflow_dispatch: # 手动触发
  release:
    types: [published]
jobs:
  build:
    # if: github.repository == 'catlair/bili-task-puppeteer'
    runs-on: ubuntu-latest
    environment: Build
    steps:

      ## 构建镜像并推送
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          MY_TAGS: echo ${{  github.ref  }} | sed -e "s/refs\/tags\/v//g"
        run: echo ${{ env.MY_TAGS }}

