name: build docker
on:
  workflow_dispatch: # 手动触发
  release:
    types: [published]
jobs:
  build:
    # if: github.repository == 'catlair/bili-task-puppeteer'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: 环境
        run: echo ${{ secrets.TEST_BILI }} >> demo1.json
      - name: Test
        run: cat demo1.json
      ## 构建镜像并推送
      - name: Publish to Registry
        # uses: elgohr/Publish-Docker-Github-Action@v5
        run: echo MY_TAGS=${{ github.ref  }} | sed -e "s/refs\/tags\/v//g"  >> $GITHUB_ENV
        
      - name: 测试结果
        run: echo ${{ env.MY_TAGS }}

      - name: 测试结果2
        run: echo $MY_TAGS
